const enc=new TextEncoder();
export default{async fetch(req,env){const url=new URL(req.url);const origin=req.headers.get('Origin')||'';const headers=cors(env,origin);if(req.method==='OPTIONS')return new Response(null,{headers});try{
 if(url.pathname==='/api/login'&&req.method==='POST'){const {pin=''}=await req.json();if(!env.ADMIN_PIN||pin.length!==12||!safeEqual(pin,env.ADMIN_PIN))return json({error:'Unauthorized'},401,headers);return json({token:await signSession(env)},200,headers)}
 if(url.pathname==='/api/token'&&req.method==='GET'){if(!env.UNISAT_API_TOKEN)return json({error:'UniSat API not configured'},503,headers);const r=await fetch('https://open-api.unisat.io/v1/indexer/brc20/QUQN/info',{headers:{Authorization:`Bearer ${env.UNISAT_API_TOKEN}`,Accept:'application/json'}});const d=await r.json();if(!r.ok||d.code!==0)return json({error:'UniSat API error'},502,headers);return json(d.data,200,headers)}
 if(url.pathname==='/api/config'&&req.method==='POST'){await requireAuth(req,env);const body=await req.json();body.version='2.0';await writeGithub(env,'assets/config.json',utf8ToB64(JSON.stringify(body,null,2)),'Update QUQN site config');return json({ok:true},200,headers)}
 if(url.pathname==='/api/upload'&&req.method==='POST'){await requireAuth(req,env);const {path,base64}=await req.json();if(!/^assets\/gallery\/[a-z0-9-]+\.webp$/.test(path||''))return json({error:'Invalid path'},400,headers);if(!base64||base64.length>7_000_000)return json({error:'Image too large'},413,headers);await writeGithub(env,path,base64,'Add QUQN gallery image');return json({ok:true,path},200,headers)}
 return json({error:'Not found'},404,headers)
 }catch(e){return json({error:e.message||'Server error'},e.status||500,headers)}}};
function cors(env,origin){const allowed=(env.ALLOWED_ORIGIN||'').split(',').map(s=>s.trim()).filter(Boolean);const ok=allowed.includes(origin);return {'content-type':'application/json; charset=utf-8','access-control-allow-origin':ok?origin:(allowed[0]||'*'),'access-control-allow-headers':'content-type, authorization','access-control-allow-methods':'GET,POST,OPTIONS','vary':'Origin','cache-control':'no-store'}}
function json(obj,status,headers){return new Response(JSON.stringify(obj),{status,headers})}
function safeEqual(a,b){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64urlText(s){return b64url(enc.encode(s))}
async function hmac(text,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text))))}
async function signSession(env){const payload=b64urlText(JSON.stringify({exp:Date.now()+12*60*60*1000}));return payload+'.'+await hmac(payload,env.SESSION_SECRET)}
async function requireAuth(req,env){let auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer ')){let e=Error('Unauthorized');e.status=401;throw e}let token=auth.slice(7),[p,s]=token.split('.');if(!p||!s||!safeEqual(s,await hmac(p,env.SESSION_SECRET))){let e=Error('Unauthorized');e.status=401;throw e}let raw=p.replace(/-/g,'+').replace(/_/g,'/');raw+= '='.repeat((4-raw.length%4)%4);let data=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(raw),c=>c.charCodeAt(0))));if(Date.now()>data.exp){let e=Error('Session expired');e.status=401;throw e}}
function utf8ToB64(s){let bytes=enc.encode(s),bin='';for(let i=0;i<bytes.length;i++)bin+=String.fromCharCode(bytes[i]);return btoa(bin)}
async function writeGithub(env,path,content,message){if(!env.GITHUB_OWNER||!env.GITHUB_REPO||!env.GITHUB_TOKEN)throw Error('GitHub Worker secrets are not configured');const branch=env.GITHUB_BRANCH||'main',api=`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${path}`;let sha;const get=await fetch(api+`?ref=${encodeURIComponent(branch)}`,{headers:ghHeaders(env)});if(get.ok)sha=(await get.json()).sha;else if(get.status!==404)throw Error('Unable to read GitHub file');const payload={message,content,branch,...(sha?{sha}:{})};const put=await fetch(api,{method:'PUT',headers:{...ghHeaders(env),'content-type':'application/json'},body:JSON.stringify(payload)});if(!put.ok)throw Error('GitHub write failed: '+await put.text())}
function ghHeaders(env){return {Authorization:`Bearer ${env.GITHUB_TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'QUQN-Manager'}}
